# Generated by Django 3.2.10 on 2021-12-24 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OauthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.IntegerField(blank=True, default=0, null=True, verbose_name='排序')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('openid', models.CharField(max_length=64, unique=True, verbose_name='openid')),
                ('name', models.IntegerField(choices=[(1, 'QQ'), (2, '微信'), (3, '微博')], default=1, verbose_name='社交平台名称')),
                ('access_token', models.CharField(help_text='有效期:3个月', max_length=500, verbose_name='临时访问票据')),
                ('refresh_token', models.CharField(help_text='当access_token过期以后,可以使用refresh_token来重新获取新的access_token和refresh_token', max_length=500, verbose_name='刷新访问票据的token')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_user', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '第三方社交账号登录用户数据',
                'verbose_name_plural': '第三方社交账号登录用户数据',
                'db_table': 'rr_oauth_user',
            },
        ),
    ]
