# Generated by Django 3.2.10 on 2021-12-28 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.IntegerField(blank=True, default=0, null=True, verbose_name='排序')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='文章')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('html_content', models.TextField(verbose_name='文章内容[html格式]')),
                ('pub_date', models.DateTimeField(default=None, null=True, verbose_name='发布时间')),
                ('access_pwd', models.CharField(blank=True, max_length=15, null=True, verbose_name='访问密码')),
                ('read_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='阅读量')),
                ('like_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='点赞量')),
                ('collect_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='收藏量')),
                ('comment_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='评论量')),
                ('reward_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='赞赏量')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 'rr_article',
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.IntegerField(blank=True, default=0, null=True, verbose_name='排序')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('group', models.CharField(blank=True, max_length=15, null=True, verbose_name='组名')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='图片地址')),
                ('sha1_files', models.CharField(blank=True, max_length=64, null=True, verbose_name='文件指纹')),
            ],
            options={
                'verbose_name': '文章图片',
                'verbose_name_plural': '文章图片',
                'db_table': 'rr_article_image',
            },
        ),
        migrations.CreateModel(
            name='ArticleSpecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.IntegerField(blank=True, default=0, null=True, verbose_name='排序')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='封面图片')),
                ('notice', models.TextField(blank=True, null=True, verbose_name='专题公告')),
                ('article_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='文章总数')),
                ('follow_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='关注数量')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='myspecials', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '专题',
                'verbose_name_plural': '专题',
                'db_table': 'rr_article_special',
            },
        ),
        migrations.CreateModel(
            name='SpecialManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.IntegerField(blank=True, default=0, null=True, verbose_name='排序')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('special', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.articlespecial', verbose_name='专题')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '专题管理员',
                'verbose_name_plural': '专题管理员',
                'db_table': 'rr_special_manager',
            },
        ),
        migrations.CreateModel(
            name='SpecialFocus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.IntegerField(blank=True, default=0, null=True, verbose_name='排序')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('special', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.articlespecial', verbose_name='专题')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '专题粉丝',
                'verbose_name_plural': '专题粉丝',
                'db_table': 'rr_special_focus',
            },
        ),
        migrations.CreateModel(
            name='ArticlePostSpecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.IntegerField(blank=True, default=0, null=True, verbose_name='排序')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.SmallIntegerField(choices=[(0, '投稿中'), (1, '等待审核'), (2, '已审核'), (3, '审核不通过')], default=0, verbose_name='审核状态')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article', verbose_name='文章')),
                ('special', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.articlespecial', verbose_name='专题')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='审核管理员')),
            ],
            options={
                'verbose_name': '专题的文章',
                'verbose_name_plural': '专题的文章',
                'db_table': 'rr_article_post_special',
            },
        ),
        migrations.CreateModel(
            name='ArticleCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.IntegerField(blank=True, default=0, null=True, verbose_name='排序')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='文集名称')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mycollections', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '文集',
                'verbose_name_plural': '文集',
                'db_table': 'rr_article_collection',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_list', to='article.articlecollection', verbose_name='文集'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='myarticles', to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
    ]
