# Generated by Django 3.2.10 on 2021-12-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlespecial',
            name='name',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='专题名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='html_content',
            field=models.TextField(blank=True, null=True, verbose_name='文章内容[html格式]'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='发布时间'),
        ),
    ]
