# Generated by Django 3.2.10 on 2022-01-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20211231_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepostspecial',
            name='post_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='投稿时间'),
        ),
    ]
