# Generated by Django 3.2.10 on 2021-12-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.IntegerField(blank=True, default=0, null=True, verbose_name='排序')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=150, verbose_name='轮播图标题')),
                ('info', models.CharField(blank=True, max_length=1000, null=True, verbose_name='备注信息')),
                ('link', models.CharField(blank=True, max_length=150, null=True, verbose_name='轮播图广告地址')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner', verbose_name='轮播图')),
                ('start_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='上架时间')),
                ('end_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='下架时间')),
                ('is_http', models.BooleanField(default=False, help_text='站内地址格式：/users/<br>站外地址格式：http://www.baidu.com', verbose_name='是否站外地址')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'db_table': 'rr_banner',
            },
        ),
    ]
